#pragma config(Sensor, S1,     Eyes,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S4,     Laser,          sensorEV3_Color)
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnLeft(){
		setMotorSpeed(RightMotor, 10);
		setMotorSpeed(LeftMotor, -10);
}

void turnRight(){
	setMotorSpeed(RightMotor, -10);
	setMotorSpeed(LeftMotor, 10);
}

void moveForwardSlow(){
		setMotorSpeed(RightMotor, 10);
		setMotorSpeed(LeftMotor, 10);
}

void moveForwardMedium(){
		setMotorSpeed(RightMotor, 30);
		setMotorSpeed(LeftMotor, 30);
}

void stopMovement(){
	setMotorSpeed(RightMotor, 0);
	setMotorSpeed(LeftMotor, 0);
}

void reverseSlow(){
	setMotorSpeed(RightMotor, -10);
	setMotorSpeed(LeftMotor, -10);
}


/*void checkRight(TSimpleColors colorName){
	resetGyro(S3);
	//if(getUSDistance(Eyes) < 10) {
	repeatUntil(getGyroDegrees(S3) >= 90 || (colorName == colorGreen)) {
			turnRight();
	}
	//}
}*/

void checkLeft(){
	resetGyro(S3);
	//if(getUSDistance(Eyes) < 10) {
	repeatUntil(getGyroDegrees(S3) <= -90) {
			turnLeft();
	}
	//}
}




void reverseDirection(){
	//Checking to see if object is within 10 CM
	resetGyro(S3);
	if(getUSDistance(Eyes) < 10) {
			repeatUntil(getGyroDegrees(S3) > 180) {
				turnRight();
			}
	}

	resetGyro(S3);
}


void checkDistance(){
	//Checking to see if object is within 10 CM
	//resetGyro(S3);
	if(getUSDistance(Eyes) < 10) {
			repeatUntil(getGyroDegrees(S3) > 180) {
				//turnLeft();
				setMotorSpeed(RightMotor, -30);
				setMotorSpeed(LeftMotor, 30);
			}
	}

	resetGyro(S3);
}

void greenLineFollow(){
	while(true){
		if (getColorName(Laser) == colorGreen){
			moveForwardSlow();

		} else {
			resetGyro(S3);

			//Check Right
			while((getColorName(Laser) != colorGreen) || (getGyroDegrees(S3) <= 20)) {
				turnRight();
				if(getColorName(Laser) == colorGreen) {
					resetGyro(S3);
					break;
				}
			}
			repeatUntil(getGyroDegrees(S3) == 0) {
				turnLeft();
			}
			while((getColorName(Laser) != colorGreen) || (getGyroDegrees(S3) >= -20)) {
				turnLeft();
				if(getColorName(Laser) == colorGreen) {
					resetGyro(S3);
					break;

				}
			}
			repeatUntil(getGyroDegrees(S3) == 0) {
				turnRight();
			}
			/*
			//Check Right
			repeatUntil(getGyroDegrees(S3) >= 30 || (getColorName(Laser) == colorGreen)) {
				turnRight();
			}//repeat until
			resetGyro(S3);
			if (getColorName(Laser) != colorGreen){
				repeatUntil (getGyroDegrees(S3) <= -30 || (getColorName(Laser) == colorGreen)){
					turnLeft();
				}
				//stopMovement();
			}
			if (getColorName(Laser) != colorGreen){
				repeatUntil (getGyroDegrees(S3) == 0|| (getColorName(Laser) == colorGreen)){
					turnLeft();
				}
				//stopMovement();
			}
			*/
			//stopMovement();

			//stopMovement();
			//Check Left
			/*repeatUntil(getGyroDegrees(S3) <= -30 || (getColorName(Laser)  == colorGreen)) {
			turnLeft();
			}
			while (getGyroDegrees(S3) <= 0){
				turnRight();
			}
			stopMovement();*/


		}//else
	}//while
}
void greenLineFollowV2(){
	while (getColorName(Laser) == colorGreen){
		moveForwardSlow();
	}
	while (getColorName(Laser) != colorGreen){
		turnLeft();
	}
}

void correctOrientation(){
//	resetGyro(S3);
	//check right
	repeatUntil(getColorName(Laser) == colorGreen || getGyroDegrees(S3) > 90){

		//resetGyro(S3);
		//while((getGyroDegrees(S3) >= -90)) {
		writeDebugStreamLine("%d", getGyroDegrees(S3));
		turnRight();
	}
	//CheckLeft
	repeatUntil(getColorName(Laser) != colorGreen || getGyroDegrees(S3) < -90){
		//resetGyro(S3);
		//while((getGyroDegrees(S3) >= -90)) {
		writeDebugStreamLine("%d", getGyroDegrees(S3));
		turnLeft();
	}//if statement
}

void greenLineFollowV4(){
	if (getColorName(Laser) == colorGreen){
		moveForwardSlow();
	} else {
		correctOrientation();
	}//if statement

}


void greenLineFollowV3(){
	while (true){

		if (getColorName(Laser) == colorGreen){
			moveForwardSlow();
		} else {
			if(getColorName(Laser) != colorGreen && getGyroDegrees(S3) > -90){
				//resetGyro(S3);
				//while((getGyroDegrees(S3) >= -90)) {
				writeDebugStreamLine("%d", getGyroDegrees(S3));
				turnLeft();
			}
			if(getColorName(Laser) != colorGreen && getGyroDegrees(S3) < -90){
				//resetGyro(S3);
				//while((getGyroDegrees(S3) >= -90)) {
					writeDebugStreamLine("%d", getGyroDegrees(S3));
					turnRight();
			}//if statement

		}//else

			//}
			//Check Right

			/*while((getGyroDegrees(S3) <= 90)) {
				turnRight();
				if(getColorName(Laser) == colorGreen) {
					resetGyro(S3);
					break;
				}
			}
			repeatUntil(getGyroDegrees(S3) == 0) {
				turnLeft();
			}
			while((getColorName(Laser) != colorGreen) || (getGyroDegrees(S3) >= -90)) {
				turnLeft();
				if(getColorName(Laser) == colorGreen) {
					resetGyro(S3);
					break;
				}
			}
			repeatUntil(getGyroDegrees(S3) == 0) {
				turnRight();
			}*/

	}//while

}//greenfollowline v3

void findGreenLineNoGyro(){
	while(true){
		if (getColorName(Laser) == colorGreen){
			moveForwardSlow();
		}
		while (getColorName(Laser) != colorGreen){
			turnLeft();
			sleep(3000);
			turnRight();
			sleep(6000);
			stopMovement();
		}

	}



}

void findGreenLine(){
	while(true){
		if(getColorName(Laser) == colorGreen){
			writeDebugStreamLine("This is GREEN!");
			setMotorSpeed(RightMotor, 0);
			setMotorSpeed(LeftMotor, 0);
			return;
		} else {
			writeDebugStreamLine("NOT Green!");
			setMotorSpeed(RightMotor, 10);
			setMotorSpeed(LeftMotor, 10);

		}
	}
}


task main()
{
	//long red;
	//long green;
	//long blue;

	//findGreenLine();
	//sleep(1000);
	resetGyro(S3);
	//greenLineFollowV3();
	greenLineFollowV4();

	//findGreenLineNoGyro();

	//greenLineFollow();


	//greenLineFollow();

	/*while(true) {
		//Move forward until you run into an object then reverse
		moveForwardSlow();
		reverseDirection();


		//Approach Line
		moveForwardSlow();

		if(getColorName(Laser) == colorGreen){
			writeDebugStreamLine("This is GREEN!");
			setMotorSpeed(RightMotor, 0);
			setMotorSpeed(LeftMotor, 0);
		} else {
			writeDebugStreamLine("NOT Green!");
			setMotorSpeed(RightMotor, 10);
			setMotorSpeed(LeftMotor, 10);
		}
		//Check Left side


		//Check Right side



		//reverseDirection();

	/*
		getColorRGB(Laser, red, green, blue);
		//getColorName(nDeviceIndex)
		while (true){
			resetGyro(S3);

			repeatUntil(getGyroDegrees(S3) > 45) {
				setMotorSpeed(RightMotor, -15);
				setMotorSpeed(LeftMotor, 15);
			}

			setMotorSpeed(RightMotor, 0);
			setMotorSpeed(LeftMotor, 0);
			sleep(500);

			repeatUntil(getGyroDegrees(S3) < -45) {
				setMotorSpeed(RightMotor, 15);
				setMotorSpeed(LeftMotor, -15);
			}

			setMotorSpeed(RightMotor, 0);
			setMotorSpeed(LeftMotor, 0);
			sleep(500);
			//Checking to see if object is within 10 CM
			//checkDistance();
			/*if(getUSDistance(Eyes) < 10) {
				setMotorSpeed(RightMotor, 0);
				setMotorSpeed(LeftMotor, 0);
			} else {
				setMotorSpeed(RightMotor, 15);
				setMotorSpeed(LeftMotor, 15);
			}*/

				/*
				if(getColorName(Laser) == colorGreen){
				writeDebugStreamLine("This is GREEN!");
				setMotorSpeed(RightMotor, 0);
				setMotorSpeed(LeftMotor, 0);
			} else {
				writeDebugStreamLine("NOT Green!");
				setMotorSpeed(RightMotor, 10);
				setMotorSpeed(LeftMotor, 10);
				*/
		//}//while loop

		//setMotorSpeed(nMotorIndex, 50);

	//}//while loop

		//writeDebugStreamLine("Color: %d, %d, %d", red, green, blue);
    //sleep(200);
	//}
}
